### PR TITLE
add css, html and js file of passenger_counter_app 

### PR DESCRIPTION
**Pull request by nngrz**

### CODE REVIEW

**Comment by balinskia** [comment]
The pull request title is incorrect - you are not adding anything to the Ning branch.

If you open a pull request, you can see from what branch you are merging into what branch. So no need to add this information to the pull request title

**Comment by balinskia** [comment]
"add css, html and js file" is also not the best name of a pull request. This can be applied to any exercise. Please rename it to something more descriptive.

**Comment by balinskia** [comment]
Typo in the pr title

**Comment by balinskia** [comment]
Would be nice if you add a screenshot to the PR's description so that I can see what you did

**Comment by nngrz** [comment]
> Would be nice if you add a screenshot to the PR's description so that I can see what you did

Screenshot 2024-07-18 at 14 39 34

**Review by balinskia — APPROVED** [review]

**Pull request merged**
